"""empty message

Revision ID: be630aba8244
Revises: 18f1fe4b575b
Create Date: 2023-02-02 21:21:25.419944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be630aba8244'
down_revision = '18f1fe4b575b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.alter_column('answer', 'create_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('question', 'create_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'create_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('answer', 'create_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_table('user')
    # ### end Alembic commands ###
